/*
* @Author: leopku
* @Date:   2017-06-28 22:13:38
* @Last Modified by:   leopku
* @Last Modified time: 2017-07-24 17:20:38
*/

'use strict'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const SWITCH_SIGNUP_DIALOG = 'SWITCH_SIGNUP_DIALOG'
export const SWITCH_LOGIN_DIALOG = 'SWITCH_LOGIN_DIALOG'
export const CATEGORY_LOAD = 'CATEGORY_LOAD'
export const CATEGORY_LOAD_SUCCESS = 'CATEGORY_LOAD_SUCCESS'
export const CATEGORY_LOAD_FAILED = 'CATEGORY_LOAD_FAILED'
export const TOPIC_LOAD = 'TOPIC_LOAD'
export const TOPIC_LOAD_SUCCESS = 'TOPIC_LOAD_SUCCESS'
export const TOPIC_LOAD_FAILED = 'TOPIC_LOAD_FAILED'
export const TOPIC_LOAD_MORE = 'TOPIC_LOAD_MORE'
export const TOPIC_RESORT = 'TOPIC_RESORT'
export const SHIFT_NEW_TOPIC = 'SHIFT_NEW_TOPIC'
export const SWITCH_NEW_TOPIC_DIALOG = 'SWITCH_NEW_TOPIC_DIALOG'
export const COMMON_LOAD = 'COMMON_LOAD'
export const COMMON_LOAD_SUCCESS = 'COMMON_LOAD_SUCCESS'
export const COMMON_LOAD_FAILED = 'COMMON_LOAD_FAILED'
export const REPLY_LOAD = 'REPLY_LOAD'
export const REPLY_LOAD_SUCCESS = 'REPLY_LOAD_SUCCESS'
export const REPLY_LOAD_FAILED = 'REPLY_LOAD_FAILED'
